### ISSUE TITLE
As someone trying to practice trading, when I submit an order, so I see it in the Open Order Panel table.

### ISSUE THREAD

**Issue by fdpilkington** [cse442-spring-2020-offering/cse442-semester-project-trading-app#12]
**Tasks:**

1. Create table to hold values.
2. Update table when buy/sell orders are placed.

**Acceptance Tests:**

1. Place orders should show up in this panel until filled.
2. Should display type, size, price, fee, and status.

**Comment by louismot** [comment]
Condensing Open Order Table and History table into one table, this is no longer needed.
